/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author tomasaraujo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkIn_buttom = new javax.swing.JButton();
        checkOut_buttom = new javax.swing.JButton();
        searchRes_buttom = new javax.swing.JButton();
        historial_buttom = new javax.swing.JButton();
        searchLod_buttom = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DIN Alternate", 0, 14)); // NOI18N
        jLabel1.setText("Buscar Reservación:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 20));

        jLabel2.setFont(new java.awt.Font("DIN Alternate", 0, 24)); // NOI18N
        jLabel2.setText("Selecciona una opción:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        checkIn_buttom.setText("Check In");
        checkIn_buttom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkIn_buttomActionPerformed(evt);
            }
        });
        jPanel1.add(checkIn_buttom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 90, 40));

        checkOut_buttom.setText("Check Out");
        jPanel1.add(checkOut_buttom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, 40));

        searchRes_buttom.setText("Buscar");
        jPanel1.add(searchRes_buttom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, 40));

        historial_buttom.setText("Historial");
        historial_buttom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historial_buttomActionPerformed(evt);
            }
        });
        jPanel1.add(historial_buttom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 90, 40));

        searchLod_buttom.setText("Buscar");
        jPanel1.add(searchLod_buttom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 80, 40));

        Save.setText("Guardar");
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 90, 40));

        jLabel3.setFont(new java.awt.Font("DIN Alternate", 0, 14)); // NOI18N
        jLabel3.setText("Check In:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("DIN Alternate", 0, 14)); // NOI18N
        jLabel4.setText("Guardar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("DIN Alternate", 0, 14)); // NOI18N
        jLabel5.setText("Check Out:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("DIN Alternate", 0, 14)); // NOI18N
        jLabel6.setText("Historial de habitación:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("DIN Alternate", 0, 14)); // NOI18N
        jLabel7.setText("Buscar hospedaje:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkIn_buttomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkIn_buttomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkIn_buttomActionPerformed

    private void historial_buttomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historial_buttomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historial_buttomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JButton checkIn_buttom;
    private javax.swing.JButton checkOut_buttom;
    private javax.swing.JButton historial_buttom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchLod_buttom;
    private javax.swing.JButton searchRes_buttom;
    // End of variables declaration//GEN-END:variables
}
